### PR TITLE
Reformat android xml files and include the necessary tools:ignore

### PR DESCRIPTION
**Pull request by gabrielluong**

### CODE REVIEW

**Comment by jsimplicio** [comment]
Hey gl,

Are the tools:ignore changes something we accidentally forgot or stripped away recently (we've implemented a new workflow so we're curious if it affected the format)? I know we're supposed to add tools:ignore="VectorPath" to complex paths but saw that your change had some different values assigned to this too (e.g. tools:ignore="VectorPath,VectorRaster"). Curious if there's something new we should be aware of.

Also curious if there's a preference for the existing order of fillColor and pathData.

Thanks!

**Comment by gabrielluong** [comment]
> Also curious if there's a preference for the existing order of fillColor and pathData.
How I went about this was that I copied each individual xml into our project in Android Studio and ran format file. This will always format things so that the ordering of these properties follow alphabetical order so `fillColor` will always appear before `pathData`. To make it easier to import the XML from acorn-icons to our project going forward, I wanted to ensure every single individual XML is now formatted correctly.

> Are the tools:ignore changes something we accidentally forgot or stripped away recently (we've implemented a new workflow so we're curious if it affected the format)? I know we're supposed to add tools:ignore="VectorPath" to complex paths but saw that your change had some different values assigned to this too (e.g. tools:ignore="VectorPath,VectorRaster"). Curious if there's something new we should be aware of.
I added some of the missing `tools:ignore="VectorPath"` that Android Studio complained about. We need `VectorRaster` for every `<path>` if `tools:targetApi="n"` appears in the XML. Technically, we didn't need to import this change back into acorn-icons. It is only necessary when we change the `fillColor` from `#000` to use our color token `@color/mozac_ui_icons_fill` in our project ([Example](https://searchfox.org/mozilla-mobile/source/firefox-android/android-components/components/ui/icons/src/main/res/drawable/mozac_ic_add_to_homescreen_24.xml#12)). However, bringing this change back into the original XML source will make this one less thing that we will have to do when importing new icons.

**Comment by JulianGaibler** [comment]
Sorry for the noise, it seems our (relatively new) Github action not only broke in the meantime but also was never tested on pull request from forks 😅

I'm trying to fix this; worst case, I run it locally and push the changes.

@gabrielluong are there any problems with us using slightl different formatting (we just run prettier on the XML) than what Android Studio returns?

**Comment by JulianGaibler** [comment]
Okay, it seems making commits on PRs that are based on forks is...complicated ([if not impossible?](https://github.com/actions/checkout/issues/455)). So I just ran the action locally and pushed. Sorry again for the noise!

**Review by jsimplicio — APPROVED** [review]

**Comment by jsimplicio** [comment]
@gabrielluong Thanks! I retitled the PR and added a description to follow our format. Hope that's ok. Also merged and cut a new release.

I also added your explanation about `VectorRaster` to the wiki here https://github.com/FirefoxUX/acorn-icons/wiki/File-format-conventions.

Julian has left another question in here for you but overall this makes sense, thank you again.

**Comment by gabrielluong** [comment]
> @gabrielluong are there any problems with us using slightl different formatting (we just run prettier on the XML) than what Android Studio returns?

I took a look at what was landed with the prettier formatting. In my opinion, I would **strongly** recommend going with what Android Studio returns. If we were diffing changes between what we imported into Android Studio (or in this case our fenix project) and what is in this repo, then I would prefer to not see formatting as being the difference because this affects all files.

**Pull request merged**
